server:
  port: 9001

spring:
  application:
    name: CUSTOMER-SERVICE


eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

resilience4j.retry:
  instances:
    retryService:
      maxRetryAttempts: 5
      waitDuration: 5000

resilience4j.ratelimiter:
  instances:
    basic:
      limitForPeriod: 3
      limitRefreshPeriod: 1
      timeoutDuration: 5s